/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gina' at '24/2/16 12:34 PM' with Gradle 2.11
 *
 * @author gina, @date 24/2/16 12:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
